name: test

on:
  push:
  pull_request:

env:
  GO111MODULE: on

jobs:
  test-unix:
    strategy:
      fail-fast: false
      matrix:
        platform:
        - ubuntu
        go:
        - 16
    name: '${{ matrix.platform }} | 1.${{ matrix.go }}.x'
    runs-on: ${{ matrix.platform }}-latest
    steps:
    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: 1.${{ matrix.go }}.x
    - name: checkout
      uses: actions/checkout@v2
    - name: Build
      env:
        GOPROXY: "https://proxy.golang.org"
      run: go build .

    - name: Build for mac
      env:
        GOPROXY: "https://proxy.golang.org"
	GOOS: darwin
	GOARCH: amd64
      run: go build -o crontosaurus-mac .

    - name: Test
      env:
        GOPROXY: "https://proxy.golang.org"
      run: go test -v .
    - name: Integration test
      run: ./integration_test.sh
    - name: Upload linux artifact
      uses: actions/upload-artifact@v2
      with:
        name: crontosaurus-linux
        path: ./crontosaurus
    - name: Upload mac artifact
      uses: actions/upload-artifact@v2
      with:
        name: crontosaurus-mac
        path: ./crontosaurus-mac
